name: insight-vector
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - ipywidgets
  - nbformat>=4.2.0
  - bertopic==0.16.2
  - chromadb==0.4.17
  - openai==1.51.2
  - langchain==0.2.16
  - langchain-community==0.2.16
  - langchain-openai==0.1.25
  - langchain-chroma==0.1.4
  - numpy
  - pandas==2.2.3
  - plotly::plotly==5.24.1
  - pytorch::pytorch==2.5.0
  - sentence-transformers==3.2.0
  - streamlit==1.39.0